import { z } from "zod";

export const trendStateSchema = z.enum(["new", "rising", "steady", "falling", "archived"]);
export const confidenceSchema = z.enum(["high", "medium", "low"]);
export const evidenceStatusSchema = z.enum(["verified", "lead_only", "failed"]);
export const sourceTypeSchema = z.enum(["招聘", "生产实践", "行业报告", "评测研究", "政策"]);
export type TrendState = z.infer<typeof trendStateSchema>;
export type Confidence = z.infer<typeof confidenceSchema>;
export type EvidenceStatus = z.infer<typeof evidenceStatusSchema>;
export type SourceType = z.infer<typeof sourceTypeSchema>;

export interface Problem {
  id:string; index:string; name:string; definition:string; score:number; delta:number; state:TrendState; confidence:Confidence;
  evidence:number; publishers:number; signal:string; history:number[]; color:string; industries:string[]; roles:string[]; skills:string[];
  aliases:string[]; firstSeenAt:string; lastSeenAt:string; judgement:string; whyNow:string; project:string; projectBrief:string; metrics:string[]; nextSteps:string[];
}
export interface Evidence { id:string; problemId:string; title:string; publisher:string; type:SourceType; status:EvidenceStatus; authority:"A"|"B"|"C"; region:"中国"|"全球"; date:string; excerpt:string; skills:string[]; url:string; }
export interface Signal { id:string; type:SourceType; title:string; source:string; date:string; relativeTime:string; impact:number; problemId:string; summary:string; }

const rows: Array<Omit<Problem,"index"|"evidence"|"publishers">> = [
  {id:"agent-evals",name:"Agent 评测闭环",definition:"从单次答案评分转向任务结果、执行轨迹和线上反馈。",score:88,delta:14,state:"rising",confidence:"high",signal:"生产实践",history:[31,35,39,44,48,52,58,61,68,73,79,88],color:"#8b7cff",industries:["企业服务","软件研发","金融"],roles:["AI 应用工程师","评测工程师","算法工程师"],skills:["Evals","Tracing","LLM Judge","回归测试"],aliases:["Agent Evals","智能体评估"],firstSeenAt:"2026-06-18",lastSeenAt:"2026-09-12",judgement:"企业开始把评测作为独立工程系统，而不是上线前的一次性测试。",whyNow:"Agent 会调用工具并改变环境，错误具有传播性。仅检查最终文本已经无法解释失败，也无法支撑版本回归。",project:"生产轨迹驱动的 Agent 评测台",projectBrief:"采集任务轨迹、环境终态和人工反馈，对不同模型与工作流版本进行可重复对照。",metrics:["任务成功率","Pass^k","轨迹合规率","人机一致率"],nextSteps:["建立 30 条真实任务基线","记录工具调用与环境终态","加入失败聚类与版本回归"]},
  {id:"tool-reliability",name:"工具调用可靠性",definition:"让 Agent 在真实系统中可重试、可审计、可恢复且不越权。",score:84,delta:11,state:"rising",confidence:"high",signal:"招聘 + 工程",history:[38,40,43,47,49,55,58,63,67,71,77,84],color:"#54d6d0",industries:["企业服务","金融","电商"],roles:["后端工程师","AI 应用工程师","安全工程师"],skills:["状态机","幂等","权限策略","补偿事务"],aliases:["Function Calling 稳定性","Agent 执行安全"],firstSeenAt:"2026-05-30",lastSeenAt:"2026-09-12",judgement:"工具调用的竞争点正在从“能调用”转向“副作用可控”。",whyNow:"一旦 Agent 连接订单、支付、邮件或生产系统，重复执行和越权会直接产生业务损失。",project:"带策略引擎的安全工具 Agent",projectBrief:"用执行账本、幂等键、审批策略和补偿动作管理高风险工具调用。",metrics:["重复副作用率","恢复成功率","越权拦截率","接管比例"],nextSteps:["定义工具风险等级","实现幂等与重放","注入超时、乱序和重复调用"]},
  {id:"industry-workflows",name:"行业工作流重构",definition:"把 AI 嵌入制造、金融、医疗和物流的完整业务链路。",score:79,delta:18,state:"new",confidence:"high",signal:"行业报告",history:[19,22,23,28,31,36,43,48,54,61,69,79],color:"#f2b563",industries:["制造","物流","医疗","能源"],roles:["解决方案工程师","AI 产品经理","应用工程师"],skills:["流程建模","领域知识","系统集成","Human-in-the-loop"],aliases:["AI+行业","垂直工作流"],firstSeenAt:"2026-07-04",lastSeenAt:"2026-09-11",judgement:"传统行业的机会正在从知识助手迁移到可度量的流程节点。",whyNow:"行业模型和通用模型已经足够易用，真正稀缺的是把权限、数据和人工决策组织成完整闭环的人。",project:"制造异常处理协作 Agent",projectBrief:"模拟设备异常从识别、查手册、生成工单到人工确认的完整流程。",metrics:["处理时间","建议采纳率","错误升级率","人工节省时长"],nextSteps:["选择一个窄行业流程","画出角色与系统边界","用业务指标而非回答分数验收"]},
  {id:"enterprise-rag",name:"权限化企业 RAG",definition:"同时解决知识时效、权限继承、引用和静默失败。",score:74,delta:5,state:"steady",confidence:"high",signal:"工程实践",history:[44,46,50,53,57,60,62,64,68,70,72,74],color:"#ff8fa3",industries:["企业服务","金融","政务"],roles:["AI 应用工程师","数据工程师","后端工程师"],skills:["Hybrid Search","Rerank","ACL","引用审计"],aliases:["企业知识治理","动态 RAG"],firstSeenAt:"2026-04-20",lastSeenAt:"2026-09-10",judgement:"企业 RAG 的核心问题不再是向量检索，而是权限、版本和可归因性。",whyNow:"内部知识持续变化，检索成功但引用过期或越权，比直接回答失败更难被发现。",project:"时态与权限感知的企业知识库",projectBrief:"构造多部门、多个版本的文档集，验证检索权限、过期引用和拒答策略。",metrics:["Recall@k","过期引用率","越权泄露率","有据回答率"],nextSteps:["构造权限矩阵","加入文档版本冲突","分别评测检索与生成"]},
  {id:"inference-economics",name:"推理成本工程",definition:"在效果、延迟、并发和成本之间建立可观测的选择。",score:71,delta:9,state:"rising",confidence:"medium",signal:"基础设施",history:[27,30,34,37,43,47,51,55,59,63,67,71],color:"#6da8ff",industries:["云计算","企业服务","消费应用"],roles:["AI Infra 工程师","后端工程师","平台工程师"],skills:["Routing","Caching","Batching","Observability"],aliases:["LLM FinOps","模型路由"],firstSeenAt:"2026-06-03",lastSeenAt:"2026-09-09",judgement:"模型选择正在从静态配置变为按任务价值动态路由。",whyNow:"应用调用量上升后，单位任务成功成本比单 Token 价格更能反映真实效率。",project:"质量约束下的多模型路由器",projectBrief:"基于任务难度、延迟预算和质量下限，动态选择模型、缓存和降级策略。",metrics:["单次成功成本","P95 延迟","降级成功率","质量下限违约率"],nextSteps:["定义三类任务难度","建立质量/成本基线","实现路由与缓存对照"]},
  {id:"long-memory",name:"可纠错长期记忆",definition:"处理偏好漂移、冲突更新、选择性遗忘与删除传播。",score:67,delta:-2,state:"falling",confidence:"medium",signal:"评测研究",history:[39,44,49,54,61,66,70,73,72,70,69,67],color:"#b68cff",industries:["消费应用","医疗","教育"],roles:["算法工程师","AI 应用工程师","研究工程师"],skills:["Temporal Retrieval","Memory Policy","实体解析","遗忘评测"],aliases:["Agent Memory","长期用户理解"],firstSeenAt:"2026-03-11",lastSeenAt:"2026-09-08",judgement:"记忆仍重要，但市场开始质疑“接入记忆组件就会变好”的简单假设。",whyNow:"错误或过期记忆会长期污染决策。研究重点正从存储容量转向写入门控、纠错和遗忘。",project:"偏好漂移记忆基准",projectBrief:"构造跨月用户偏好变化，比较全历史、RAG Memory 和事件记忆策略。",metrics:["有效命中率","过期偏好误用率","纠正残留率","Token 节省率"],nextSteps:["建立时间变化数据集","实现三种记忆基线","加入纠正和删除测试"]},
  {id:"context-engineering",name:"上下文工程",definition:"在有限 Token 中持续保留任务需要的高信号状态。",score:65,delta:7,state:"rising",confidence:"medium",signal:"生产实践",history:[25,28,30,34,37,41,46,49,53,57,61,65],color:"#5fc7a8",industries:["软件研发","研究","企业服务"],roles:["AI 应用工程师","提示工程师","平台工程师"],skills:["Context Compression","状态摘要","检索策略","Token Budget"],aliases:["Context Management","上下文治理"],firstSeenAt:"2026-06-26",lastSeenAt:"2026-09-07",judgement:"上下文窗口变长没有消除上下文选择，反而放大了低信号内容的成本。",whyNow:"长程任务不断产生中间结果，需要决定哪些进入工作记忆、哪些外置、哪些可以遗忘。",project:"长任务上下文预算器",projectBrief:"对研究型任务实施分层状态、动态压缩和检索，并与全历史上下文比较。",metrics:["任务完成率","压缩损失率","Token 消耗","恢复准确率"],nextSteps:["定义最小充分状态","记录每轮上下文构成","比较摘要、检索和全历史"]},
  {id:"ai-security",name:"Agent 权限与安全",definition:"限制外部内容、工具和凭据扩大后的攻击与破坏半径。",score:62,delta:10,state:"rising",confidence:"medium",signal:"政策 + 工程",history:[18,21,24,28,31,35,39,44,48,52,57,62],color:"#ff7777",industries:["金融","政务","企业服务"],roles:["AI 安全工程师","平台工程师","后端工程师"],skills:["Sandbox","Prompt Injection","最小权限","审计"],aliases:["Agent Security","工具安全"],firstSeenAt:"2026-07-01",lastSeenAt:"2026-09-06",judgement:"模型防护正在让位于系统级隔离和最小权限设计。",whyNow:"Agent 接触网页、邮件和内部系统后，任何外部内容都可能影响高权限动作。",project:"最小权限 Agent 沙箱",projectBrief:"设计按任务签发的短期工具权限，验证注入攻击、凭据隔离和出网控制。",metrics:["攻击拦截率","误阻断率","权限收敛度","审计覆盖率"],nextSteps:["建立威胁模型","实现任务级能力令牌","构造提示注入攻击集"]},
  {id:"multimodal-agents",name:"多模态任务理解",definition:"让 Agent 在图像、语音、视频和界面状态中保持一致推理。",score:58,delta:3,state:"steady",confidence:"low",signal:"研究",history:[30,32,34,37,40,44,47,50,52,54,56,58],color:"#e29dff",industries:["医疗","零售","工业"],roles:["多模态算法工程师","研究工程师","AI 应用工程师"],skills:["Vision-Language","事件理解","Grounding","多模态评测"],aliases:["Multimodal Agent","视觉智能体"],firstSeenAt:"2026-05-15",lastSeenAt:"2026-09-04",judgement:"多模态 Agent 的机会正在从识别单张图片转向持续事件理解。",whyNow:"工业、医疗和零售任务需要把视觉状态与工具动作对齐，而现有评测仍偏静态。",project:"视觉操作任务评测集",projectBrief:"构造多步骤界面或设备操作任务，评估视觉定位、状态更新和动作正确性。",metrics:["Grounding 准确率","步骤完成率","状态误判率","恢复率"],nextSteps:["选择一个可模拟环境","标注观察—动作轨迹","加入界面变化干扰"]},
  {id:"coding-agents",name:"长程软件工程 Agent",definition:"让编码 Agent 跨上下文完成真实仓库任务并可恢复。",score:56,delta:12,state:"new",confidence:"medium",signal:"招聘 + 研究",history:[12,14,17,20,24,29,33,38,42,47,51,56],color:"#85a7ff",industries:["软件研发","开发者工具","云计算"],roles:["研发工程师","Agent 工程师","开发工具工程师"],skills:["Agent Harness","代码检索","测试生成","检查点"],aliases:["Coding Agent","软件工程智能体"],firstSeenAt:"2026-07-20",lastSeenAt:"2026-09-12",judgement:"编码 Agent 的评价单位正在从补全片段升级为可验收的仓库级任务。",whyNow:"真实开发任务需要数小时甚至数天，Agent 必须跨上下文保存状态、运行测试并处理环境漂移。",project:"可断点续跑的仓库任务 Agent",projectBrief:"让 Agent 在受控仓库完成多阶段修改，支持检查点、测试验证和中断恢复。",metrics:["仓库任务完成率","测试通过率","中断恢复率","重复动作率"],nextSteps:["挑选 20 个真实 Issue","记录计划与文件状态","注入上下文中断并验证恢复"]}
];

export const problems:Problem[]=rows.map((p,i)=>({...p,index:String(i+1).padStart(2,"0"),evidence:4,publishers:4}));
const publishers=["头部互联网公司","企业工程团队","产业研究机构","高校实验室","公共就业服务","云服务商","开源社区","金融科技团队","制造数字化团队","开发者工具团队"];
const sourceTypes:SourceType[]=["招聘","生产实践","行业报告","评测研究","政策"];
const titleTemplates=["岗位职责出现新的工程能力要求","生产复盘暴露规模化瓶颈","行业调研显示投入开始迁移","公开评测加入真实任务约束","人才目录强调复合型能力"];
export const evidenceRecords:Evidence[]=problems.flatMap((p,pi)=>Array.from({length:5},(_,ei)=>{const type=sourceTypes[(pi+ei)%sourceTypes.length];const status:EvidenceStatus=ei===4?(pi%3===0?"failed":"lead_only"):"verified";return{id:`EV-${String(pi*5+ei+1).padStart(3,"0")}`,problemId:p.id,title:`${p.name}：${titleTemplates[ei]}`,publisher:publishers[(pi*2+ei)%publishers.length],type,status,authority:ei<2?"A":ei<4?"B":"C",region:pi%3===0?"全球":"中国",date:`2026-09-${String(12-((pi+ei)%9)).padStart(2,"0")}`,excerpt:status==="verified"?`演示证据显示，“${p.name}”开始与${p.skills.slice(0,2).join("、")}共同出现在真实任务要求中。`:status==="lead_only"?"页面仅提供标题或摘要，正文尚未完成验证，因此不计入趋势得分。":"页面访问失败，保留为待复核线索，不参与统计。",skills:p.skills.slice(ei%2,ei%2+2),url:`https://example.com/mock/${p.id}/${ei+1}`}}));
const signalEvidence=[...problems.map(p=>evidenceRecords.find(e=>e.problemId===p.id&&e.status==="verified")!),...problems.slice(0,8).map(p=>evidenceRecords.find(e=>e.problemId===p.id&&e.status==="verified"&&e.type!==sourceTypes[problems.indexOf(p)%sourceTypes.length])!)];
export const signals:Signal[]=signalEvidence.map((e,i)=>{const p=problems.find(x=>x.id===e.problemId)!;return{id:`SIG-${String(i+1).padStart(2,"0")}`,type:e.type,title:e.title,source:`${e.publisher} · ${e.type}样本`,date:e.date,relativeTime:i===0?"2 小时前":i<3?"昨天":`${Math.min(i,7)} 天前`,impact:Math.max(2,Math.min(9,Math.round(p.delta/2)+(i%3))),problemId:e.problemId,summary:e.excerpt}});
export const overview={generatedAt:"2026-09-12T09:40:00+08:00",collectionCount:evidenceRecords.length,verifiedCount:evidenceRecords.filter(e=>e.status==="verified").length,publisherCount:new Set(evidenceRecords.map(e=>e.publisher)).size,problemCount:problems.length,window:"最近 12 周",judgement:"企业关注点正在从模型能力转向系统兑现。",judgementDetail:"新增信号更多指向评测、工具稳定性与行业流程重构。能证明系统在失败条件下仍然可控，比再做一个对话 Demo 更有区分度。"};
